---
rbac:
  create: true

alertmanager:
  enabled: false

pushgateway:
  enabled: false

server:
  ingress:
    enabled: true
    hosts:
      - prometheus.192.168.26.11.nip.io
    annotations:
      kubernetes.io/ingress.class: nginx
  
  persistentVolume:
    enabled: false
