apiVersion: v1
kind: Service
metadata:
  name: demoapp
  namespace: default
spec:
  selector:
    app: demoapp
  type: LoadBalancer
  ports:
  - name: demoapp-lb
    port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 31000