---
ingress:
  enabled: true
  hosts:
    - grafana.192.168.26.11.nip.io
  annotations:
    kubernetes.io/ingress.class: nginx

persistence:
  enabled: false

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: prometheus
      type: prometheus
      url: http://prometheus-server
      access: proxy
      isDefault: true