apiVersion: v1
kind: Pod
metadata:
 name: nginx
spec:
 affinity:
   nodeAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
       nodeSelectorTerms:
       - matchExpressions:
         - key: mynode
           operator: In
           values: 
           - worker-1       
         - key: mynode
           operator: NotIn
           values:
           - worker-3

 containers:
 - name: nginx
   image: nginx
